# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecolor < Formula
  desc "Colorize your kubectl output"
  homepage "https://github.com/kubecolor/kubecolor"
  version "0.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.0.21/kubecolor_0.0.21_Darwin_arm64.tar.gz"
      sha256 "689707d994f8240a6d383dc98363917637c26694c90bf2373b109e9f150101d6"

      def install
        bin.install "kubecolor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.0.21/kubecolor_0.0.21_Darwin_x86_64.tar.gz"
      sha256 "cee9069d318669d6a46b1fe132b38f0e255d3d5a71ff638e1e08eab32fef4bf4"

      def install
        bin.install "kubecolor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.0.21/kubecolor_0.0.21_Linux_x86_64.tar.gz"
      sha256 "9028dd05aaf22ab6f4c19d5c80e17e02093b3f82d36a2938262b52822338f46d"

      def install
        bin.install "kubecolor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.0.21/kubecolor_0.0.21_Linux_arm64.tar.gz"
      sha256 "19d7ea4fddf5a15912576b650f511a9d2602194c6edf83c63a1f972cb0501883"

      def install
        bin.install "kubecolor"
      end
    end
  end
end
