# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecolor < Formula
  desc "Colorize your kubectl output"
  homepage "https://github.com/kubecolor/kubecolor"
  version "0.3.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.3.3/kubecolor_0.3.3_darwin_amd64.tar.gz"
      sha256 "14171e307366d85c181ff28b73d9f1281e7c4719fa8c7261cb68abe095231a00"

      def install
        bin.install "kubecolor"
      end
    end
    on_arm do
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.3.3/kubecolor_0.3.3_darwin_arm64.tar.gz"
      sha256 "19b1db19635a4f3448c4276acca32979450f7ac3bf1af617422c50fe0c536693"

      def install
        bin.install "kubecolor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubecolor/kubecolor/releases/download/v0.3.3/kubecolor_0.3.3_linux_amd64.tar.gz"
        sha256 "5ef7ccdc08aca7a82cb29d2d37d7f39245aae711cc47234d10d204e2ec00a7f5"

        def install
          bin.install "kubecolor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubecolor/kubecolor/releases/download/v0.3.3/kubecolor_0.3.3_linux_arm64.tar.gz"
        sha256 "68433ef17525db2ffe178f269585407a0d9410ebb9c3254650fca68b65d527cf"

        def install
          bin.install "kubecolor"
        end
      end
    end
  end
end
