# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecolor < Formula
  desc "Colorize your kubectl output"
  homepage "https://github.com/kubecolor/kubecolor"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.1.0/kubecolor_0.1.0_darwin_arm64.tar.gz"
      sha256 "b57ce0170e4d7fcaf07ca07239de7ba048f4a9b44e73b6a8307ba191b6724963"

      def install
        bin.install "kubecolor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.1.0/kubecolor_0.1.0_darwin_amd64.tar.gz"
      sha256 "4d189a74c9df3bb255e5da17afd9e50d1a748c25f0929fe3c589a77ec9db15c9"

      def install
        bin.install "kubecolor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.1.0/kubecolor_0.1.0_linux_amd64.tar.gz"
      sha256 "3f98ecfa0dcdf5ef39e6f6eb8cd175d207c3aa7791d91f0e23f72e9fc6ac1693"

      def install
        bin.install "kubecolor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubecolor/kubecolor/releases/download/v0.1.0/kubecolor_0.1.0_linux_arm64.tar.gz"
      sha256 "1761f0ee31395caec3ae865bfec0dcb4c394ba326339933c6bf38ffbd87af9d4"

      def install
        bin.install "kubecolor"
      end
    end
  end
end
